name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      HLINT_VERSION: "3.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC + Cabal)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.14.1"
          cabal-version: "3.16.1.0"

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project*') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install HLint
        uses: haskell-actions/hlint-setup@v2
        with:
          version: ${{ env.HLINT_VERSION }}

      - name: Lint
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "test"]'
          fail-on: warning

      - name: Build
        run: make build

      - name: Test
        run: make test
